services:
  postgres:
    image: postgres:15-alpine
    container_name: backstage-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: backstage
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backstage -d backstage"]
      interval: 30s
      timeout: 10s
      retries: 5

  backstage-app:
    build: .
    container_name: backstage-app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "7007:7007"
      - "443:443"
      - "80:80"
      - "8080:8080"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=backstage
      - POSTGRES_PASSWORD=backstage_password
      - POSTGRES_DB=backstage
    volumes:
      - /Users/jaime.henao/arheanja/Backstage-solutions/backstage-app-devc:/app
      - backstage_data:/app/backstage/data
    working_dir: /app
    tty: true
    stdin_open: true

volumes:
  postgres_data:
    driver: local
  backstage_data:
    driver: local
