services:
  postgres:
    image: postgres:15-alpine
    container_name: backstage-postgres-devc
    restart: unless-stopped
    environment:
      POSTGRES_DB: backstage
      POSTGRES_USER: backstage
      POSTGRES_PASSWORD: backstage_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backstage -d backstage"]
      interval: 30s
      timeout: 10s
      retries: 5

  backstage-app:
    build: .
    container_name: backstage-app-devc
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "argocd.test.com:host-gateway"
      - "grafana.test.com:host-gateway"
      - "prometheus.test.com:host-gateway"
      - "backstage.test.com:host-gateway"
      - "backstage.kind.local:host-gateway"
    ports:
      - "3001:3001"
      - "7008:7008"
      - "4443:443"
      - "8081:80"
      - "8083:8083"
      - "8080:8080"
      - "8001:8001"
      - "3010:3010"
      - "9090:9090"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=backstage
      - POSTGRES_PASSWORD=backstage_password
      - POSTGRES_DB=backstage
      # 👇 clave para Node.js >= 20
      - NODE_OPTIONS=--no-node-snapshot
    volumes:
      - /Users/jaime.henao/arheanja/Backstage-solutions/backstage-app-devc:/app
      - backstage_data:/app/backstage/data
      - gitconfig_data:/home/node/.config
      # Persistencia para Minikube y Kubernetes
      - minikube_data:/root/.minikube
      - kube_data:/root/.kube
      - kube_data_node:/home/node/.kube
      # Persistencia para ArgoCD (si se usa almacenamiento local)
      - argocd_data:/home/node/.argocd
    privileged: true
    working_dir: /app
    tty: true
    stdin_open: true

volumes:
  postgres_data:
    driver: local
  backstage_data:
    driver: local
  gitconfig_data:
    driver: local
  minikube_data:
    driver: local
  kube_data:
    driver: local
  kube_data_node:
    driver: local
  argocd_data:
    driver: local
