---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-read
rules:
- apiGroups: [""]
  resources:
    - pods
    - pods/log
    - pods/status
    - services
    - services/status
    - configmaps
    - limitranges
    - resourcequotas
    - replicasets
    - replicasets/status
    - deployments
    - deployments/status
    - nodes
    - namespaces
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
    - deployments
    - deployments/status
    - replicasets
    - replicasets/status
    - daemonsets
    - daemonsets/status
    - statefulsets
    - statefulsets/status
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
    - deployments
    - deployments/status
    - replicasets
    - replicasets/status
    - ingresses
    - ingresses/status
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources:
    - ingresses
    - ingresses/status
  verbs: ["get", "list", "watch"]
- apiGroups: ["autoscaling"]
  resources:
    - horizontalpodautoscalers
    - horizontalpodautoscalers/status
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
    - jobs
    - jobs/status
    - cronjobs
    - cronjobs/status
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources:
    - pods
    - nodes
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backstage-read
subjects:
- kind: ServiceAccount
  name: backstage
  namespace: default