apiVersion: v1
kind: Namespace
metadata:
  name: sample-app
  labels:
    backstage.io/kubernetes-id: sample-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: sample-app
  labels:
    app: sample-app
    backstage.io/kubernetes-id: sample-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
        backstage.io/kubernetes-id: sample-application
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-service
  namespace: sample-app
  labels:
    app: sample-app
    backstage.io/kubernetes-id: sample-application
spec:
  selector:
    app: sample-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app-config
  namespace: sample-app
  labels:
    backstage.io/kubernetes-id: sample-application
data:
  environment: "development"
  version: "1.0.0"